---
- name: Create users
  user: name={{ item.name }} groups={{ item.addgroups | default('') }} shell=/bin/bash append=yes
  with_items: "{{ users }}"

- include_tasks: nested_authorized_key.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: outer_item
